# Generated by Django 3.2.8 on 2021-12-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('following', 'follower')},
        ),
    ]
